test.reconfig_packs({"chromaforge"}, {})
test.new_world("demo", "67", "builtin:default")
assert(world.get_generator() == "builtin:default")
coroutine.yield()
assert(world.get_total_time() > 0.0)
print(world.get_total_time())
test.close_world(true)
assert(not world.is_open())
