#include "ContentPack.h"

#include <stdexcept>

#include "../files/files.h"
#include "../coders/json.h"
#include "../logger/Logger.h"
#include "../files/engine_paths.h"
#include "../definitions.h"

const std::string ContentPack::PACKAGE_FILENAME = "package.json";
const std::string ContentPack::CONTENT_FILENAME = "content.json";
const std::filesystem::path ContentPack::BLOCKS_FOLDER = std::filesystem::path("blocks");
const std::filesystem::path ContentPack::ITEMS_FOLDER = "items";

contentpack_error::contentpack_error(std::string packId, std::filesystem::path folder, std::string message) : std::runtime_error(message), packId(packId), folder(folder) {
}

std::string contentpack_error::getPackId() const {
    return packId;
}
std::filesystem::path contentpack_error::getFolder() const {
    return folder;
}

std::filesystem::path ContentPack::getContentFile() const {
    return folder/std::filesystem::path(CONTENT_FILENAME);
}

bool ContentPack::is_pack(std::filesystem::path folder) {
    return std::filesystem::is_regular_file(folder/std::filesystem::path(PACKAGE_FILENAME));
}

ContentPack ContentPack::read(std::filesystem::path folder) {
    auto root = files::read_json(folder/std::filesystem::path(PACKAGE_FILENAME));
    ContentPack pack;

    root->str("id", pack.id);
    root->str("title", pack.title);
    root->str("version", pack.version);
    pack.folder = folder;

    if (pack.id == "none") {
        LOG_ERROR("Content-pack id is none: {}", folder.u8string());
        Logger::getInstance().flush();
        throw contentpack_error(pack.id, folder, "Content-pack id is none");
    }
    return pack;
}

void ContentPack::scan(std::filesystem::path rootfolder, std::vector<ContentPack>& packs) {
    if (!std::filesystem::is_directory(rootfolder)) return;

    for (auto entry : std::filesystem::directory_iterator(rootfolder)) {
        std::filesystem::path folder = entry.path();
        if (!std::filesystem::is_directory(folder)) continue;
        if (!is_pack(folder)) continue;
        packs.push_back(read(folder));
    }
}

std::vector<std::string> ContentPack::worldPacksList(std::filesystem::path folder) {
    std::filesystem::path listfile = folder/std::filesystem::path("packs.list");
    if (!std::filesystem::is_regular_file(listfile)) {
        LOG_WARN("packs.list not found (will be created)");
        files::write_string(listfile, "# autogenerated, do not modify\n" DEFAULT_CONTENT_NAMESPACE "\n");
    }
    return files::read_list(listfile);
}

std::filesystem::path ContentPack::findPack(const EnginePaths* paths, std::filesystem::path worldDir, std::string name) {
    auto folder = worldDir/std::filesystem::path("content")/std::filesystem::path(name);
    if (std::filesystem::is_directory(folder)) return folder;

    folder = paths->getResources()/std::filesystem::path("content")/std::filesystem::path(name);
    if (std::filesystem::is_directory(folder)) return folder;

    LOG_ERROR("Could not to find pack '{}'", name);
    Logger::getInstance().flush();
    throw contentpack_error(name, folder, "Could not to find pack '" + name + "'");
}

void ContentPack::readPacks(const EnginePaths* paths, std::vector<ContentPack>& packs, const std::vector<std::string>& packnames, std::filesystem::path worldDir) {
    for (const auto& name : packnames) {
        std::filesystem::path packfolder = ContentPack::findPack(paths, worldDir, name);
        packs.push_back(ContentPack::read(packfolder));
    }
}
