#include "ContentPack.h"

#include <stdexcept>
#include <algorithm>

#include "../files/files.h"
#include "../coders/json.h"
#include "../debug/Logger.h"
#include "../files/engine_paths.h"
#include "../core_content_defs.h"
#include "../data/dynamic.h"

const std::string ContentPack::PACKAGE_FILENAME = "package.json";
const std::string ContentPack::CONTENT_FILENAME = "content.json";
const std::filesystem::path ContentPack::BLOCKS_FOLDER = std::filesystem::path("blocks");
const std::filesystem::path ContentPack::ITEMS_FOLDER = "items";
const std::vector<std::string> ContentPack::RESERVED_NAMES = {"res", "abs", "local", BUILTIN_CONTENT_NAMESPACE, "user", "world", "none", "null"};

contentpack_error::contentpack_error(std::string packId, std::filesystem::path folder, std::string message) : std::runtime_error(message), packId(packId), folder(folder) {
}

std::string contentpack_error::getPackId() const {
    return packId;
}
std::filesystem::path contentpack_error::getFolder() const {
    return folder;
}

std::filesystem::path ContentPack::getContentFile() const {
    return folder/std::filesystem::path(CONTENT_FILENAME);
}

bool ContentPack::is_pack(std::filesystem::path folder) {
    return std::filesystem::is_regular_file(folder/std::filesystem::path(PACKAGE_FILENAME));
}

static void checkContentPackId(const std::string& id, const std::filesystem::path& folder) {
    if (id.length() < 2 || id.length() > 24) {
        LOG_ERROR("Content-pack id '{}' length is out of range [2, 24]", id);
        throw contentpack_error(id, folder, "Content-pack id length is out of range [2, 24]");
    }

    if (isdigit(id[0])) {
        LOG_ERROR("Content-pack id '{}' must not start with a digit", id);
        throw contentpack_error(id, folder, "Content-pack id must not start with a digit");
    }

    for (char c : id) {
        if (!isalnum(c) && c != '_') {
            LOG_ERROR("Illegal character in content-pack id '{}'", id);
            throw contentpack_error(id, folder, "Illegal character in content-pack id");
        }
    }

    if (std::find(ContentPack::RESERVED_NAMES.begin(), ContentPack::RESERVED_NAMES.end(), id) != ContentPack::RESERVED_NAMES.end()) {
        LOG_ERROR("Content-pack id '{}' is reserved", id);
        throw contentpack_error(id, folder, "This content-pack id is reserved");
    }
}

ContentPack ContentPack::read(std::filesystem::path folder) {
    auto root = files::read_json(folder/std::filesystem::path(PACKAGE_FILENAME));
    ContentPack pack;

    root->str("id", pack.id);
    root->str("title", pack.title);
    root->str("version", pack.version);
    root->str("creator", pack.creator);
    root->str("description", pack.description);
    pack.folder = folder;

    auto dependencies = root->list("dependencies");
    if (dependencies) {
        for (size_t i = 0; i < dependencies->size(); ++i) {
            pack.dependencies.push_back(
                {DependencyLevel::Required, dependencies->str(i)}
            );
        }
    }

    if (pack.id == "none") {
        LOG_ERROR("Content-pack id is not specified: {}", folder.u8string());
        throw contentpack_error(pack.id, folder, "Content-pack id is not specified");
    }
    checkContentPackId(pack.id, folder);

    return pack;
}

void ContentPack::scanFolder(std::filesystem::path folder, std::vector<ContentPack>& packs) {
    if (!std::filesystem::is_directory(folder)) return;

    for (auto entry : std::filesystem::directory_iterator(folder)) {
        std::filesystem::path folder = entry.path();
        if (!std::filesystem::is_directory(folder)) continue;
        if (!is_pack(folder)) continue;
        try {
            packs.push_back(read(folder));
        } catch (const contentpack_error& err) {
            LOG_ERROR("package.json error at '{}': {}", err.getFolder().u8string(), err.what());
        } catch (const std::runtime_error& err) {
            LOG_ERROR("{}", err.what());
        }
    }
}

std::vector<std::string> ContentPack::worldPacksList(std::filesystem::path folder) {
    std::filesystem::path listfile = folder/std::filesystem::path("packs.list");
    if (!std::filesystem::is_regular_file(listfile)) {
        LOG_WARN("packs.list not found (will be created)");
        files::write_string(listfile, "# autogenerated, do not modify\n" + CHROMAFORGE_CONTENT_NAMESPACE + "\n");
    }
    return files::read_list(listfile);
}

std::filesystem::path ContentPack::findPack(const EnginePaths* paths, std::filesystem::path worldDir, std::string name) {
    auto folder = worldDir/std::filesystem::path("content")/std::filesystem::path(name);
    if (std::filesystem::is_directory(folder)) return folder;

    folder = paths->getUserfiles()/std::filesystem::path("content")/std::filesystem::path(name);
    if (std::filesystem::is_directory(folder)) return folder;

    folder = paths->getResources()/std::filesystem::path("content")/std::filesystem::path(name);
    return folder;
}

ContentPackRuntime::ContentPackRuntime(
    ContentPack info, 
    scriptenv env
) : info(info), 
    env(std::move(env)) {}

ContentPackRuntime::~ContentPackRuntime() {
}
