[forest]
parameters = [
    {weight=1, value=0},
    {weight=0.5, value=0.2}
]
layers = [
    {below-sea-level=false, height=1, block="chromaforge:moss"},
    {below-sea-level=false, height=7, block="chromaforge:dirt"},
    {height=-1, block="chromaforge:stone"},
    {height=1, block="chromaforge:bedrock"}
]
sea-layers = [
    {height=-1, block="chromaforge:water"}
]
plant-chance = 0.4
plants = [
    {weight=1, block="chromaforge:grass"},
    {weight=0.03, block="chromaforge:poppy"},
    {weight=0.03, block="chromaforge:dandelion"},
    {weight=0.03, block="chromaforge:marigold"},
    {weight=0.03, block="chromaforge:daisy"}
]
structure-chance = 0.032
structures = [
    {name="oak0", weight=1},
    {name="oak1", weight=1},
    {name="birch0", weight=1},
    {name="tower", weight=0.002}
]

[desert]
parameters = [
    {weight=1.0, value=1},
    {weight=0.8, value=0}
]
layers = [
    {height=6, block="chromaforge:sand"},
    {height=-1, block="chromaforge:stone"},
    {height=1, block="chromaforge:bedrock"}
]
sea-layers = [
    {height=-1, block="chromaforge:water"}
]
plant-chance = 0.02
plants =[
    {weight=1, block="chromaforge:dead_bush"}
]

[plains]
parameters = [
    {weight=0.8, value=0.5},
    {weight=0.8, value=0.0}
]
layers = [
    {below-sea-level=false, height=1, block="chromaforge:moss"},
    {below-sea-level=false, height=5, block="chromaforge:dirt"},
    {height=-1, block="chromaforge:stone"},
    {height=1, block="chromaforge:bedrock"}
]
sea-layers = [
    {height=-1, block="chromaforge:water"}
]
plant-chance = 0.3
plants = [
    {weight=1, block="chromaforge:grass"},
    {weight=0.03, block="chromaforge:poppy"},
    {weight=0.03, block="chromaforge:dandelion"}
]
structure-chance=0.0001
structures = [
    {name="oak0", weight=1},
    {name="birch0", weight=1}
]
