#include "WorldFiles.h"

#include <cassert>
#include <cstdint>
#include <fstream>
#include <sstream>
#include <cstring>
#include <utility>

#include "coders/byte_utils.h"
#include "coders/json.h"
#include "constants.h"
#include "content/Content.h"
#include "core_content_defs.h"
#include "data/dynamic.h"
#include "items/Inventory.h"
#include "items/Item.h"
#include "lighting/Lightmap.h"
#include "math/voxmaths.h"
#include "objects/Player.h"
#include "physics/Hitbox.h"
#include "typedefs.h"
#include "util/data_io.h"
#include "voxels/Block.h"
#include "voxels/Chunk.h"
#include "voxels/voxel.h"
#include "window/Camera.h"
#include "world/World.h"
#include "debug/Logger.h"
#include "settings.h"
#include "objects/Entity.h"

WorldFiles::WorldFiles(const std::filesystem::path& directory) : directory(directory), regions(directory) {
}

WorldFiles::WorldFiles(const std::filesystem::path& directory, const DebugSettings& settings) : WorldFiles(directory) {
    generatorTestMode = settings.generatorTestMode.get();
    doWriteLights = settings.doWriteLights.get();
	regions.generatorTestMode = generatorTestMode;
    regions.doWriteLights = doWriteLights;
}

WorldFiles::~WorldFiles(){
}

void WorldFiles::createDirectories() {
    std::filesystem::create_directories(directory/std::filesystem::path("data"));
    std::filesystem::create_directories(directory/std::filesystem::path("content"));
}

std::filesystem::path WorldFiles::getPlayerFile() const {
	return directory/std::filesystem::path("player.json");
}

std::filesystem::path WorldFiles::getWorldFile() const {
	return directory/std::filesystem::path(WORLD_FILE);
}

std::filesystem::path WorldFiles::getIndicesFile() const {
	return directory/std::filesystem::path("indices.json");
}

std::filesystem::path WorldFiles::getPacksFile() const {
	return directory/std::filesystem::path("packs.list");
}

std::filesystem::path WorldFiles::getResourcesFile() const {
    return directory/std::filesystem::path("resources.json");
}

void WorldFiles::write(const World* world, const Content* content) {
	if (world) {
		writeWorldInfo(world);
		if (!std::filesystem::exists(getPacksFile())) writePacks(world->getPacks());
	}
	if (generatorTestMode) return;
	writeIndices(content->getIndices());
	regions.write();
}

void WorldFiles::writePacks(const std::vector<ContentPack>& packs) {
	auto packsFile = getPacksFile();

	std::stringstream ss;
	ss << "# autogenerated; do not modify\n";
	for (const auto& pack : packs) {
		ss << pack.id << "\n";
	}
	files::write_string(packsFile, ss.str());
}

template<class T>
static void write_indices(const ContentUnitIndices<T>& indices, dynamic::List& list) {
    size_t count = indices.count();
    for (size_t i = 0; i < count; ++i) {
        list.put(indices.get(i)->name);
	}
}

void WorldFiles::writeIndices(const ContentIndices* indices) {
    dynamic::Map root;

    write_indices(indices->blocks, root.putList("blocks"));
    write_indices(indices->items, root.putList("items"));
    write_indices(indices->entities, root.putList("entities"));

	files::write_json(getIndicesFile(), &root);
}

void WorldFiles::writeWorldInfo(const World* world) {
	files::write_json(getWorldFile(), world->serialize().get());
}

bool WorldFiles::readWorldInfo(World* world) {
	std::filesystem::path file = getWorldFile();
	if (!std::filesystem::is_regular_file(file)) {
		LOG_WARN("World.json does not exists");
		return false;
	}

	auto root = files::read_json(file);
	world->deserialize(root.get());

	return true;
}

static void read_resources_data(
    const Content* content, 
    const dynamic::List_sptr& list,
    ResourceType type
) {
    const auto& indices = content->getIndices(type);
    for (size_t i = 0; i < list->size(); ++i) {
        auto map = list->map(i);
        std::string name;
        map->str("name", name);
        size_t index = indices.indexOf(name);
        if (index == ResourceIndices::MISSING) {
            LOG_WARN("Discard {}", name);
        } else {
            indices.saveData(index, map->map("saved"));
        }
    }
}

bool WorldFiles::readResourcesData(const Content* content) {
    std::filesystem::path file = getResourcesFile();
    if (!std::filesystem::is_regular_file(file)) {
        LOG_WARN("resources.json does not exists");
        return false;
    }
    auto root = files::read_json(file);
    for (const auto& [key, _] : root->values) {
        if (auto resType = ResourceType_from(key)) {
            if (auto arr = root->list(key)) {
                read_resources_data(content, arr, *resType);
            }
        } else {
            LOG_WARN("Unknown resource type: {}", key);
        }
    }
    return true;
}

static void erase_pack_indices(dynamic::Map* root, const std::string& id) {
	auto prefix = id + ":";
    auto blocks = root->list("blocks");
    for (uint i = 0; i < blocks->size(); ++i) {
        auto name = blocks->str(i);
        if (name.find(prefix) != 0) continue;
        auto value = blocks->getValueWriteable(i);
        *value = BUILTIN_AIR;
    }

    auto items = root->list("items");
    for (uint i = 0; i < items->size(); ++i) {
        auto name = items->str(i);
        if (name.find(prefix) != 0) continue;
        auto value = items->getValueWriteable(i);
        *value = BUILTIN_EMPTY;
    }
}

void WorldFiles::removeIndices(const std::vector<std::string>& packs) {
    auto root = files::read_json(getIndicesFile());
    for (const auto& id : packs) {
        erase_pack_indices(root.get(), id);
    }
    files::write_json(getIndicesFile(), root.get());
}

std::filesystem::path WorldFiles::getFolder() const {
    return directory;
}
