#include <files/WorldFiles.h>

#include <cassert>
#include <cstdint>
#include <fstream>
#include <sstream>
#include <cstring>
#include <utility>

#include <coders/byte_utils.h>
#include <coders/json.h>
#include <constants.h>
#include <content/Content.h>
#include <core_content_defs.h>
#include <items/Inventory.h>
#include <items/Item.h>
#include <lighting/Lightmap.h>
#include <math/voxmaths.h>
#include <objects/Player.h>
#include <physics/Hitbox.h>
#include <typedefs.h>
#include <util/data_io.h>
#include <voxels/Block.h>
#include <voxels/Chunk.h>
#include <voxels/voxel.h>
#include <window/Camera.h>
#include <world/World.h>
#include <debug/Logger.h>
#include <settings.h>
#include <objects/Entity.h>

WorldFiles::WorldFiles(const std::filesystem::path& directory) : directory(directory), regions(directory) {
}

WorldFiles::WorldFiles(const std::filesystem::path& directory, const DebugSettings& settings) : WorldFiles(directory) {
    generatorTestMode = settings.generatorTestMode.get();
    doWriteLights = settings.doWriteLights.get();
	regions.generatorTestMode = generatorTestMode;
    regions.doWriteLights = doWriteLights;
}

WorldFiles::~WorldFiles() = default;

void WorldFiles::createDirectories() {
    std::filesystem::create_directories(directory/std::filesystem::path("data"));
    std::filesystem::create_directories(directory/std::filesystem::path("content"));
}

std::filesystem::path WorldFiles::getPlayerFile() const {
	return directory/std::filesystem::path("player.json");
}

std::filesystem::path WorldFiles::getWorldFile() const {
	return directory/std::filesystem::path(WORLD_FILE);
}

std::filesystem::path WorldFiles::getIndicesFile() const {
	return directory/std::filesystem::path("indices.json");
}

std::filesystem::path WorldFiles::getPacksFile() const {
	return directory/std::filesystem::path("packs.list");
}

std::filesystem::path WorldFiles::getResourcesFile() const {
    return directory/std::filesystem::path("resources.json");
}

void WorldFiles::write(const World* world, const Content* content) {
	if (world) {
		writeWorldInfo(world->getInfo());
		if (!std::filesystem::exists(getPacksFile())) writePacks(world->getPacks());
	}
	if (generatorTestMode) return;
	if (content) writeIndices(content->getIndices());
	regions.writeAll();
}

void WorldFiles::writePacks(const std::vector<ContentPack>& packs) {
	auto packsFile = getPacksFile();

	std::stringstream ss;
	ss << "# autogenerated; do not modify\n";
	for (const auto& pack : packs) {
		ss << pack.id << "\n";
	}
	files::write_string(packsFile, ss.str());
}

template<class T>
static void write_indices(const ContentUnitIndices<T>& indices, dv::value& list) {
    for (auto unit : indices.getIterable()) {
        list.add(unit->name);
	}
}

void WorldFiles::writeIndices(const ContentIndices* indices) {
    dv::value root = dv::object();

    root["region-version"] = dv::value(REGION_FORMAT_VERSION);

    write_indices(indices->blocks, root.list("blocks"));
    write_indices(indices->items, root.list("items"));
    write_indices(indices->entities, root.list("entities"));
    files::write_json(getIndicesFile(), root);
}

void WorldFiles::writeWorldInfo(const WorldInfo& info) {
	files::write_json(getWorldFile(), info.serialize());
}

std::optional<WorldInfo> WorldFiles::readWorldInfo() {
	std::filesystem::path file = getWorldFile();
	if (!std::filesystem::is_regular_file(file)) {
		LOG_WARN("World.json does not exists");
		return std::nullopt;
	}

    auto root = files::read_json(file);
	WorldInfo info {};
    info.deserialize(root);
    return info;
}

static void read_resources_data(
    const Content* content, 
    const dv::value& list,
    ResourceType type
) {
    const auto& indices = content->getIndices(type);
    for (size_t i = 0; i < list.size(); ++i) {
        auto& map = list[i];
        const auto& name = map["name"].asString();
        size_t index = indices.indexOf(name);
        if (index == ResourceIndices::MISSING) {
            LOG_WARN("Discard {}", name);
        } else {
            indices.saveData(index, map["saved"]);
        }
    }
}

bool WorldFiles::readResourcesData(const Content* content) {
    std::filesystem::path file = getResourcesFile();
    if (!std::filesystem::is_regular_file(file)) {
        LOG_WARN("resources.json does not exists");
        return false;
    }
    auto root = files::read_json(file);
    for (const auto& [key, arr] : root.asObject()) {
        if (auto resType = ResourceType_from(key)) {
            read_resources_data(content, arr, *resType);
        } else {
            LOG_WARN("Unknown resource type: {}", key);
        }
    }
    return true;
}

void WorldFiles::patchIndicesVersion(const std::string& field, uint version) {
    std::filesystem::path file = getIndicesFile();
    if (!std::filesystem::is_regular_file(file)) {
        LOG_ERROR("{} does not exists", file.filename().u8string());
        return;
    }
    auto root = files::read_json(file);
    root[field] = version;
    files::write_json(file, root, true);
}

static void erase_pack_indices(dv::value& root, const std::string& id) {
	auto prefix = id + ":";
    auto& blocks = root["blocks"];
    for (uint i = 0; i < blocks.size(); ++i) {
        auto name = blocks[i].asString();
        if (name.find(prefix) != 0) continue;
        blocks[i] = BUILTIN_AIR;
    }

    auto& items = root["items"];
    for (uint i = 0; i < items.size(); ++i) {
        auto& name = items[i].asString();
        if (name.find(prefix) != 0) continue;
        items[i] = BUILTIN_EMPTY;
    }
}

void WorldFiles::removeIndices(const std::vector<std::string>& packs) {
    auto root = files::read_json(getIndicesFile());
    for (const auto& id : packs) {
        erase_pack_indices(root, id);
    }
    files::write_json(getIndicesFile(), root);
}

std::filesystem::path WorldFiles::getFolder() const {
    return directory;
}
