#include "WorldFiles.h"

#include <cassert>
#include <cstdint>
#include <fstream>
#include <sstream>
#include <cstring>

#include "../coders/byte_utils.h"
#include "../coders/json.h"
#include "../constants.h"
#include "../content/Content.h"
#include "../core_content_defs.h"
#include "../data/dynamic.h"
#include "../items/Inventory.h"
#include "../items/Item.h"
#include "../lighting/Lightmap.h"
#include "../math/voxmaths.h"
#include "../objects/Player.h"
#include "../physics/Hitbox.h"
#include "../typedefs.h"
#include "../util/data_io.h"
#include "../voxels/Block.h"
#include "../voxels/Chunk.h"
#include "../voxels/voxel.h"
#include "../window/Camera.h"
#include "../world/World.h"
#include "../debug/Logger.h"
#include "../settings.h"

WorldFiles::WorldFiles(std::filesystem::path directory) : directory(directory), regions(directory) {
}

WorldFiles::WorldFiles(std::filesystem::path directory, const DebugSettings& settings) : WorldFiles(directory) {
    generatorTestMode = settings.generatorTestMode.get();
    doWriteLights = settings.doWriteLights.get();
	regions.generatorTestMode = generatorTestMode;
    regions.doWriteLights = doWriteLights;
}

WorldFiles::~WorldFiles(){
}

void WorldFiles::createDirectories() {
    std::filesystem::create_directories(directory/std::filesystem::path("data"));
    std::filesystem::create_directories(directory/std::filesystem::path("content"));
}

std::filesystem::path WorldFiles::getPlayerFile() const {
	return directory/std::filesystem::path("player.json");
}

std::filesystem::path WorldFiles::getWorldFile() const {
	return directory/std::filesystem::path(WORLD_FILE);
}

std::filesystem::path WorldFiles::getIndicesFile() const {
	return directory/std::filesystem::path("indices.json");
}

std::filesystem::path WorldFiles::getPacksFile() const {
	return directory/std::filesystem::path("packs.list");
}

void WorldFiles::write(const World* world, const Content* content) {
	if (world) {
		writeWorldInfo(world);
		if (!std::filesystem::exists(getPacksFile())) writePacks(world->getPacks());
	}
	if (generatorTestMode) return;
	writeIndices(content->getIndices());
	regions.write();
}

void WorldFiles::writePacks(const std::vector<ContentPack>& packs) {
	auto packsFile = getPacksFile();

	std::stringstream ss;
	ss << "# autogenerated; do not modify\n";
	for (const auto& pack : packs) {
		ss << pack.id << "\n";
	}
	files::write_string(packsFile, ss.str());
}

void WorldFiles::writeIndices(const ContentIndices* indices) {
	dynamic::Map root;
	uint count;

	auto& blocks = root.putList("blocks");
	count = indices->countBlockDefs();
	for (uint i = 0; i < count; ++i) {
		const Block* def = indices->getBlockDef(i);
		blocks.put(def->name);
	}

	auto& items = root.putList("items");
	count = indices->countItemDefs();
	for (uint i = 0; i < count; ++i) {
		const Item* def = indices->getItemDef(i);
		items.put(def->name);
	}

	files::write_json(getIndicesFile(), &root);
}

void WorldFiles::writeWorldInfo(const World* world) {
	files::write_json(getWorldFile(), world->serialize().get());
}

bool WorldFiles::readWorldInfo(World* world) {
	std::filesystem::path file = getWorldFile();
	if (!std::filesystem::is_regular_file(file)) {
		LOG_WARN("World.json does not exists");
		return false;
	}

	auto root = files::read_json(file);
	world->deserialize(root.get());

	return true;
}

static void erase_pack_indices(dynamic::Map* root, const std::string& id) {
	auto prefix = id + ":";
    auto blocks = root->list("blocks");
    for (uint i = 0; i < blocks->size(); ++i) {
        auto name = blocks->str(i);
        if (name.find(prefix) != 0) continue;
        auto value = blocks->getValueWriteable(i);
        *value = BUILTIN_AIR;
    }

    auto items = root->list("items");
    for (uint i = 0; i < items->size(); ++i) {
        auto name = items->str(i);
        if (name.find(prefix) != 0) continue;
        auto value = items->getValueWriteable(i);
        *value = BUILTIN_EMPTY;
    }
}

void WorldFiles::removeIndices(const std::vector<std::string>& packs) {
    auto root = files::read_json(getIndicesFile());
    for (const auto& id : packs) {
        erase_pack_indices(root.get(), id);
    }
    files::write_json(getIndicesFile(), root.get());
}

std::filesystem::path WorldFiles::getFolder() const {
    return directory;
}
